name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: prettier --check .
        uses: actionsx/prettier@v2
        with:
          args: --check .
      - name: prettier --write .
        uses: actionsx/prettier@v2
        with:
          args: --write .
      - name: Git push
        run: |
          git pull origin master # 考虑延时
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git add .
          git commit -m ":star: Prettier OK"
          git push origin master
