name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NODE_VERSION: 12
  FORCE_COLOR: 3

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: prettier --check .
        uses: actionsx/prettier@v2
        with:
          args: --check .
      - name: prettier --write .
        uses: actionsx/prettier@v2
        with:
          args: --write .
